DROP TABLE
    IF EXISTS dwd.dwd_dim_book_dj;
CREATE EXTERNAL TABLE dwd.dwd_dim_book_dj (
    resource_source                STRING COMMENT '资源来源',
    resource_smjlh                 STRING COMMENT '书目记录号',
    resource_book_no               STRING COMMENT '书目记录号988$a或001',
    resource_sjly                  STRING COMMENT '数据来源',
    resource_marc                  STRING COMMENT 'MARC类型',
    resource_fmt                   STRING COMMENT '资源类型',
    resource_szptsjwybs            STRING COMMENT '(数字平台)载体表现层数据唯一标识',
    resource_djglh                 STRING COMMENT '单件管理号',
    resource_djtmh                 STRING COMMENT '单件条码号',
    resource_djgcd                 STRING COMMENT '单件馆藏地',
    resource_djgcdmc               STRING COMMENT '单件馆藏地中文名称',
    resource_djzt                  STRING COMMENT '单件状态',
    resource_djclzt                STRING COMMENT '单件处理状态',
    resource_djclztmc              STRING COMMENT '单件处理状态名称',
    resource_djclztdisplay         INT COMMENT '单件处理状态显示状态(0: 可见，1：不可见)',
    resource_djjcbs1               STRING COMMENT '单件卷册标识1',
    resource_djjcbs2               STRING COMMENT '单件卷册标识2',
    resource_djssh                 STRING COMMENT '单件索书号',
    resource_djdessh               STRING COMMENT '单件第二索书号',
    resource_djzllx                STRING COMMENT '单件资料类型',
    resource_djms                  STRING COMMENT '单件描述',
    resource_djjg                  STRING COMMENT '单件价格',
    resource_djccdjh               STRING COMMENT '单件财产登记号',
    resource_djccdjrq              STRING COMMENT '单件财产登记日期',
    resource_djddh                 STRING COMMENT '单件订单号',
    resource_djfpxx                STRING COMMENT '单件发票信息',
    resource_djopaczs              STRING COMMENT '单件OPAC注释',
    resource_djltzs                STRING COMMENT '单件流通注释',
    resource_djnbzs                STRING COMMENT '单件内部注释',
    resource_djfpzs                STRING COMMENT '单件发票注释',
    resource_djfdrq                STRING COMMENT '单件发订日期',
    resource_djgxrq                STRING COMMENT '单件更新日期',
    resource_djfwqx                STRING COMMENT '单件访问权限',
    resource_djsyxz                STRING COMMENT '单件使用限制',
    resource_djly                  STRING COMMENT '单件来源',
    resource_djtsbs                STRING COMMENT '单件特殊标识',
    resource_dzbbdj                STRING COMMENT '电子版本单件',
    resource_fzpdj                 STRING COMMENT '复制品单件',
    resource_djxgzrz               STRING COMMENT '单件相关责任者',
    resource_djxgzrfs              STRING COMMENT '单件相关责任方式',
    resource_djjzsj                STRING COMMENT '单件捐赠事件',
    resource_gcbq                  STRING COMMENT '单册馆藏标签',
    resource_fbscz                 STRING COMMENT '单件复本收藏者',
    resource_zdyyjg                STRING COMMENT '该字段的应用机构',
    resource_djcfly                STRING COMMENT '单件采访来源',
    resource_djcflydz              STRING COMMENT '单件采访来源地址',
    resource_djcfff                STRING COMMENT '单件采访方法',
    resource_djcfrq                STRING COMMENT '单件采访日期',
    resource_zzzlztxs              STRING COMMENT '专指资料(载体形式)',
    resource_gzddyyjg              STRING COMMENT '该字段的应用机构',
    resource_zzzl                  STRING COMMENT '专指资料',
    resource_lslcxx                STRING COMMENT '历史流传信息',
    resource_lslcxxxgtpwybs        STRING COMMENT '历史流传信息相关图片唯一标识',
    resource_lslcxxyyjg            STRING COMMENT '应用机构',
    resource_pz                    STRING COMMENT '批注',
    resource_pzxgtpwybs            STRING COMMENT '批注相关图片唯一标识',
    resource_pzyyjg                STRING COMMENT '应用机构',
    resource_djqszt                STRING COMMENT '单件缺损状态',
    resource_djqsyyjg              STRING COMMENT '应用机构',
    resource_djfmtpwybs            STRING COMMENT '单件封面图片唯一标识',
    resource_djfdtpwybs            STRING COMMENT '单件封底图片唯一标识',
    resource_djtmytpwybs           STRING COMMENT '单件题名页图片唯一标识',
    resource_djbqytpwybs           STRING COMMENT '单件版权页图片唯一标识',
    resource_djjzz                 STRING COMMENT '单件捐赠者',
    resource_djzzz                 STRING COMMENT '单件转赠者',
    resource_jzfz                  STRING COMMENT '捐赠附注',
    resource_update_time           STRING COMMENT '数据更新时间',
    resource_sync_time             STRING COMMENT '数据同步时间',
    resource_del                   INT    COMMENT '删除标识（0：未删除，1：已删除）'
)
COMMENT '单件实体属性数据表'
PARTITIONED BY (partition_date STRING COMMENT '数据同步分区日期，格式：YYYY-MM-DD')
STORED AS PARQUET
LOCATION
  '/data/hive/warehouse/dwd.db/dwd_dim_book_dj';
